   # service.yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: lifesync-web
   spec:
     selector:
       app: lifesync-web
     ports:
     - port: 80
       targetPort: 3000
     type: LoadBalancer